os:
  - linux

language: node_js

before_install:
- export LANG=en_US.UTF-8
- npm install npm@latest -g
- npm install -g ionic cordova

script:
- npm install
- ionic platform add browser
- ionic build platform
- ls

