os:
- linux
language: node_js
node_js:
- '6'
addons: ssh_known_hosts:162.243.118.87
before_install:
- ls
- openssl aes-256-cbc -K $encrypted_c74b358449ec_key -iv $encrypted_c74b358449ec_iv -in deploy-key.enc -out ~\/.ssh/deploy-key -d

- ls 
- rm deploy.enc
- chmod 600 deploy
- mv deploy_fbtrb ~/.ssh/deploy

- ls ~/.ssh/

- export LANG=en_US.UTF-8
- npm install npm@latest -g
- npm install -g ionic cordova

install:
- npm install
- mkdir www

script:
- ionic platform add browser
- ionic build browser
- ls
- ls www/
- $CMND -i ~/.ssh/deploy $PARAMS $SRC_PATH $USER$SERVER_IP$DEST_PATH
