os:
- linux

language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=6.7.0

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-installer
    - lib32stdc++6
    - lib32z1

before_install:

- openssl aes-256-cbc -K $encrypted_c74b358449ec_key -iv $encrypted_c74b358449ec_iv
  -in fbtrb_deploy.enc -out fbtrb_deploy -d
- chmod 600 fbtrb_deploy
- export LANG=en_US.UTF-8

# - nvm install $NODE_VERSION
# - npm install -g gulp bower cordova ionic

# install:
# - mkdir www
# - bower update

# before_script:

# - echo $JAVA_HOME
# - java -version
# - export JAVA_HOME=/usr/lib/jvm/java-8-oracle

# - wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
# - tar -xvf android-sdk_r24.4-linux.tgz

# - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
# - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-25.0.2
# - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-25
# - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
# - echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
# - export ANDROID_HOME=$PWD/android-sdk-linux
# - export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.2

script:
# - ionic platform remove android
# - ionic platform add android
# - cordova platform update android@6.1.0

# - ionic plugin add cordova-plugin-device
# - ionic plugin add cordova-plugin-splashscreen
# - cordova plugin add cordova-plugin-network-information
# - ionic plugin add cordova-plugin-x-toast
# - ionic plugin add cordova-plugin-geolocation
# - cordova plugin add cordova-plugin-file
# - cordova plugin add cordova-plugin-file-transfer

# - cordova plugins

# - ionic resources

- $CMND -r -o StrictHostKeyChecking=no -i fbtrb_deploy main.js CLOUD_CODE_DEST >/dev/null

# - ionic build android
# - $CMND -r -o StrictHostKeyChecking=no -i fbtrb_deploy $AND_SRC $DEST >/dev/null

# - ionic platform add browser
# - ionic build browser
# - $CMND -r -o StrictHostKeyChecking=no -i fbtrb_deploy $SRC $DEST >/dev/null
- ls -la 
- ssh -o StrictHostKeyChecking=no -i fbtrb_deploy server ' pm2 restart 2; exit;'

after_script:
- rm -rf *