os:
- linux

language: java

jdk:
  - oraclejdk8

env:
  - NODE_VERSION=6.7.0

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - oracle-java8-installer
    - lib32stdc++6
    - lib32z1

before_install:

- openssl aes-256-cbc -K $encrypted_c74b358449ec_key -iv $encrypted_c74b358449ec_iv
  -in fbtrb_deploy.enc -out fbtrb_deploy -d
- chmod 600 fbtrb_deploy
- export LANG=en_US.UTF-8

- nvm install $NODE_VERSION


install:

before_script:

- echo $JAVA_HOME
- java -version
- export JAVA_HOME=/usr/lib/jvm/java-8-oracle

- wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
- tar -xvf android-sdk_r24.4-linux.tgz
- ls -la ./android-sdk-linux/
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-25.0.3
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-25
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/25.0.3

- ls -la ./android-sdk-linux/platforms
- ls -la ./android-sdk-linux/tools


script:
