language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "0.6"
  - "iojs"

os:
  - linux

before_install:
- export LANG=en_US.UTF-8
- npm install -g npm
- npm install -g ionic cordova

script:
- npm install
- ls
