os:
  - linux

language: node_js
node_js:
  - "6"

before_install:
- export LANG=en_US.UTF-8
- npm install npm@latest -g
- npm install -g ionic cordova

install:


script:
- npm install
- mkdir www
- ionic platform add browser
- ionic build browser
- ls

