os:
- linux

language: node_js

node_js:
- '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - openjdk-8-jdk
    - lib32stdc++6
    - lib32z1
env:
  CXX=g++-4.8

before_install:
- openssl aes-256-cbc -K $encrypted_c74b358449ec_key -iv $encrypted_c74b358449ec_iv
  -in fbtrb_deploy.enc -out fbtrb_deploy -d
- chmod 600 fbtrb_deploy
- export LANG=en_US.UTF-8
- npm install npm@latest -g
- npm install -g gulp bower cordova ionic

install:
- npm install
- mkdir www
- bower update

before_script:
- wget http://dl.google.com/android/android-sdk_r24.4-linux.tgz
- tar -xvf android-sdk_r24.4-linux.tgz
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter platform-tools
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter build-tools-23.0.2
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter android-23
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-support
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-android-m2repository
- echo y | ./android-sdk-linux/tools/android update sdk --no-ui --all --filter extra-google-m2repository
- export ANDROID_HOME=$PWD/android-sdk-linux
- export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools:$ANDROID_HOME/build-tools/23.0.2

script:
- ionic platform remove android
- ionic platform add android
- ionic build android

- ionic platform add browser
- ionic build browser
- $CMND -r -o StrictHostKeyChecking=no -i fbtrb_deploy $SRC $DEST

- ls ionic info